# Generated by Django 3.2.3 on 2022-11-27 03:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20221127_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookstore.book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 3, 36, 13, 348427, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2022, 11, 27, 3, 36, 13, 348407, tzinfo=utc)),
        ),
    ]
