# Generated by Django 3.2.3 on 2022-11-28 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_auto_20221127_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 16, 56, 45, 223902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 16, 56, 45, 223882, tzinfo=utc)),
        ),
    ]
