# Generated by Django 3.2.3 on 2022-11-28 17:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0012_auto_20221128_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2022, 12, 3, 17, 10, 55, 643923, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='start_time',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 17, 10, 55, 643903, tzinfo=utc)),
        ),
    ]
